version: 0.2

phases:
  pre_build:
    commands:
      - echo testing
  build:
    commands:
      - echo building
      - zip -r output.zip imageConsumer.py
      - new_version=$(aws lambda update-function-code --function-name imageConsumer --zip-file fileb://./output.zip --publish | jq '.Version')
      - echo $new_version
      - current_version=$(aws lambda get-alias --function-name imageConsumer --name Prod | jq '.FunctionVersion')
  post_build:
    commands:
      - echo "values are"
      - echo new version is $new_version
      - echo current version is $current_version
      - printf '{"version":0.0,"Resources":[{"imageConsumer":{"Type":"AWS::Lambda::Function","Properties":{"Name":"imageConsumer","Alias":"Prod","CurrentVersion":%s,"TargetVersion":%s}}}]}' $current_version $new_version > appspec.json
      - aws s3 cp appspec.json s3://sqs-images-test/appspec.json
      - aws deploy create-deployment --application-name Test-Application-Lambda --deployment-group-name Test-Deployment-Lambda --s3-location bucket=sqs-images-test,bundleType=JSON,key=appspec.json
